export const GET_THEME_LIST = 'GET_THEME_LIST';
export const GET_THEME_ITEM = 'GET_THEME_ITEM';
export const THEME_ITEM_UPDATE = 'THEME_ITEM_UPDATE';
export const THEME_ITEM_DELETE = 'THEME_ITEM_DELETE';
export const THEME_CREATE = 'THEME_CREATE';

export const THEME_LOADING = 'THEME_LOADING';
export const THEME_IS_CREATE = 'THEME_IS_CREATE';
export const THEME_IS_UPDATE = 'THEME_IS_UPDATE';
export const THEME_IS_DELETE = 'THEME_IS_DELETE';
