export const GET_MEMBERSHIP_LIST = 'GET_MEMBERSHIP_LIST';
export const GET_MEMBERSHIP_ITEM = 'GET_MEMBERSHIP_ITEM';
export const MEMBERSHIP_ITEM_UPDATE = 'MEMBERSHIP_ITEM_UPDATE';
export const MEMBERSHIP_ITEM_IN_ACTIVE = 'MEMBERSHIP_ITEM_IN_ACTIVE';
export const MEMBERSHIP_CREATE = 'MEMBERSHIP_CREATE';

export const MEMBERSHIP_LOADING = 'MEMBERSHIP_LOADING';
export const MEMBERSHIP_IS_CREATE = 'MEMBERSHIP_IS_CREATE';
export const MEMBERSHIP_IS_UPDATE = 'MEMBERSHIP_IS_UPDATE';
export const MEMBERSHIP_IS_DELETE = 'MEMBERSHIP_IS_DELETE';
