export const GET_ENQUIRY_LIST = 'GET_ENQUIRY_LIST';
export const GET_ENQUIRY_ITEM = 'GET_ENQUIRY_ITEM';
export const ENQUIRY_ITEM_UPDATE = 'ENQUIRY_ITEM_UPDATE';
export const ENQUIRY_ITEM_IN_ACTIVE = 'ENQUIRY_ITEM_IN_ACTIVE';
export const ENQUIRY_CREATE = 'ENQUIRY_CREATE';

export const ENQUIRY_LOADING = 'ENQUIRY_LOADING';
export const ENQUIRY_IS_CREATE = 'ENQUIRY_IS_CREATE';
export const ENQUIRY_IS_UPDATE = 'ENQUIRY_IS_UPDATE';
export const ENQUIRY_IS_DELETE = 'ENQUIRY_IS_DELETE';
