export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_PRODUCT_ITEM = 'GET_PRODUCT_ITEM';
export const PRODUCT_ITEM_UPDATE = 'PRODUCT_ITEM_UPDATE';
export const PRODUCT_ITEM_IN_ACTIVE = 'PRODUCT_ITEM_IN_ACTIVE';
export const PRODUCT_CREATE = 'PRODUCT_CREATE';

export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const PRODUCT_IS_CREATE = 'PRODUCT_IS_CREATE';
export const PRODUCT_IS_UPDATE = 'PRODUCT_IS_UPDATE';
export const PRODUCT_IS_DELETE = 'PRODUCT_IS_DELETE';
