export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST';
export const GET_CATEGORY_ITEM = 'GET_CATEGORY_ITEM';
export const CATEGORY_ITEM_UPDATE = 'CATEGORY_ITEM_UPDATE';
export const CATEGORY_ITEM_IN_ACTIVE = 'CATEGORY_ITEM_IN_ACTIVE';
export const CATEGORY_CREATE = 'CATEGORY_CREATE';

export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const CATEGORY_IS_CREATE = 'CATEGORY_IS_CREATE';
export const CATEGORY_IS_UPDATE = 'CATEGORY_IS_UPDATE';
export const CATEGORY_IS_DELETE = 'CATEGORY_IS_DELETE';
