export const GET_BLOCK_LIST = 'GET_BLOCK_LIST';
export const GET_BLOCK_ITEM = 'GET_BLOCK_ITEM';
export const BLOCK_ITEM_UPDATE = 'BLOCK_ITEM_UPDATE';
export const BLOCK_ITEM_DELETE = 'BLOCK_ITEM_DELETE';
export const BLOCK_CREATE = 'BLOCK_CREATE';

export const BLOCK_LOADING = 'BLOCK_LOADING';
export const BLOCK_IS_CREATE = 'BLOCK_IS_CREATE';
export const BLOCK_IS_UPDATE = 'BLOCK_IS_UPDATE';
export const BLOCK_IS_DELETE = 'BLOCK_IS_DELETE';
