export const GET_PUSH_NOTIFICATION_DETAILS = 'GET_PUSH_NOTIFICATION_DETAILS';
export const PUSH_NOTIFICATION_LOADING = 'PUSH_NOTIFICATION_LOADING';
export const GET_PUSH_NOTIFICATION_LIST = 'GET_PUSH_NOTIFICATION_LIST';
