export const CHANGE_PROFILE = 'CHANGE_PROFILE';

export const SETTINGS = {
  APP_VERSION: {
    APPVERSION: 'v1.0',
  },
};

export const PUSH_NOTIFICATION_STATUS = {
  NEW: 'NEW',
  PUSH: 'PUSH',
  RE_PUSH: 'RE_PUSH',
};

export const PUSH_NOTIFICATION_TYPE = {
  ALL_STUDENT: 'ALL_STUDENT',
  ALL_PARENT: 'ALL_PARENT',
  ALL_TUTOR: 'ALL_TUTOR',
  CUSTOMIZE: 'CUSTOMIZE',
};
