export const GET_PAGE_LIST = 'GET_PAGE_LIST';
export const GET_PAGE_ITEM = 'GET_PAGE_ITEM';
export const PAGE_ITEM_UPDATE = 'PAGE_ITEM_UPDATE';
export const PAGE_ITEM_DELETE = 'PAGE_ITEM_DELETE';
export const PAGE_CREATE = 'PAGE_CREATE';

export const PAGE_LOADING = 'PAGE_LOADING';
export const PAGE_IS_CREATE = 'PAGE_IS_CREATE';
export const PAGE_IS_UPDATE = 'PAGE_IS_UPDATE';
export const PAGE_IS_DELETE = 'PAGE_IS_DELETE';
