export const GET_POST_LIST = 'GET_POST_LIST';
export const GET_POST_ITEM = 'GET_POST_ITEM';
export const POST_ITEM_UPDATE = 'POST_ITEM_UPDATE';
export const POST_ITEM_DELETE = 'POST_ITEM_DELETE';
export const POST_CREATE = 'POST_CREATE';

export const POST_LOADING = 'POST_LOADING';
export const POST_IS_CREATE = 'POST_IS_CREATE';
export const POST_IS_UPDATE = 'POST_IS_UPDATE';
export const POST_IS_DELETE = 'POST_IS_DELETE';
