export const GET_PROMOTION_LIST = 'GET_PROMOTION_LIST';
export const GET_PROMOTION_ITEM = 'GET_PROMOTION_ITEM';
export const PROMOTION_ITEM_UPDATE = 'PROMOTION_ITEM_UPDATE';
export const PROMOTION_ITEM_IN_ACTIVE = 'PROMOTION_ITEM_IN_ACTIVE';
export const PROMOTION_CREATE = 'PROMOTION_CREATE';

export const PROMOTION_LOADING = 'PROMOTION_LOADING';
export const PROMOTION_IS_CREATE = 'PROMOTION_IS_CREATE';
export const PROMOTION_IS_UPDATE = 'PROMOTION_IS_UPDATE';
export const PROMOTION_IS_DELETE = 'PROMOTION_IS_DELETE';
