export const GET_ORDERS_LIST = 'GET_ORDERS_LIST';
export const GET_ORDERS_ITEM = 'GET_ORDERS_ITEM';
export const ORDERS_ITEM_UPDATE = 'ORDERS_ITEM_UPDATE';
export const ORDERS_ITEM_IN_ACTIVE = 'ORDERS_ITEM_IN_ACTIVE';
export const ORDERS_CREATE = 'ORDERS_CREATE';

export const ORDERS_LOADING = 'ORDERS_LOADING';
export const ORDERS_IS_CREATE = 'ORDERS_IS_CREATE';
export const ORDERS_IS_UPDATE = 'ORDERS_IS_UPDATE';
export const ORDERS_IS_DELETE = 'ORDERS_IS_DELETE';
export const ORDERS_IS_SEND = 'ORDERS_IS_SEND';
