export const GET_CUSTOMER_LIST = 'GET_CUSTOMER_LIST';
export const GET_CUSTOMER_ITEM = 'GET_CUSTOMER_ITEM';
export const CUSTOMER_ITEM_UPDATE = 'CUSTOMER_ITEM_UPDATE';
export const CUSTOMER_ITEM_IN_ACTIVE = 'CUSTOMER_ITEM_IN_ACTIVE';
export const CUSTOMER_CREATE = 'CUSTOMER_CREATE';

export const CUSTOMER_LOADING = 'CUSTOMER_LOADING';
export const CUSTOMER_IS_CREATE = 'CUSTOMER_IS_CREATE';
export const CUSTOMER_IS_UPDATE = 'CUSTOMER_IS_UPDATE';
export const CUSTOMER_IS_DELETE = 'CUSTOMER_IS_DELETE';
