export const GET_COLOR_LIST = 'GET_COLOR_LIST';
export const GET_COLOR_ITEM = 'GET_COLOR_ITEM';
export const COLOR_ITEM_UPDATE = 'COLOR_ITEM_UPDATE';
export const COLOR_ITEM_IN_ACTIVE = 'COLOR_ITEM_IN_ACTIVE';
export const COLOR_CREATE = 'COLOR_CREATE';

export const COLOR_LOADING = 'COLOR_LOADING';
export const COLOR_IS_CREATE = 'COLOR_IS_CREATE';
export const COLOR_IS_UPDATE = 'COLOR_IS_UPDATE';
export const COLOR_IS_DELETE = 'COLOR_IS_DELETE';
