export const GET_ADDRESS_LIST = 'GET_ADDRESS_LIST';
export const GET_ADDRESS_ITEM = 'GET_ADDRESS_ITEM';
export const ADDRESS_ITEM_UPDATE = 'ADDRESS_ITEM_UPDATE';
export const ADDRESS_ITEM_IN_ACTIVE = 'ADDRESS_ITEM_IN_ACTIVE';
export const ADDRESS_CREATE = 'ADDRESS_CREATE';

export const ADDRESS_LOADING = 'ADDRESS_LOADING';
export const ADDRESS_IS_CREATE = 'ADDRESS_IS_CREATE';
export const ADDRESS_IS_UPDATE = 'ADDRESS_IS_UPDATE';
export const ADDRESS_IS_DELETE = 'ADDRESS_IS_DELETE';
