export const GET_APPROVAL_REQUEST_LIST = 'GET_APPROVAL_REQUEST_LIST';
export const GET_APPROVAL_REQUEST_ITEM = 'GET_APPROVAL_REQUEST_ITEM';
export const APPROVAL_REQUEST_ITEM_UPDATE = 'APPROVAL_REQUEST_ITEM_UPDATE';
export const APPROVAL_REQUEST_ITEM_IN_ACTIVE =
  'APPROVAL_REQUEST_ITEM_IN_ACTIVE';
export const APPROVAL_REQUEST_CREATE = 'APPROVAL_REQUEST_CREATE';

export const APPROVAL_REQUEST_LOADING = 'APPROVAL_REQUEST_LOADING';
export const APPROVAL_REQUEST_IS_CREATE = 'APPROVAL_REQUEST_IS_CREATE';
export const APPROVAL_REQUEST_IS_UPDATE = 'APPROVAL_REQUEST_IS_UPDATE';
