export const GET_POST_CATEGORY_LIST = 'GET_POST_CATEGORY_LIST';
export const GET_POST_CATEGORY_ITEM = 'GET_POST_CATEGORY_ITEM';
export const POST_CATEGORY_ITEM_UPDATE = 'POST_CATEGORY_ITEM_UPDATE';
export const POST_CATEGORY_ITEM_DELETE = 'POST_CATEGORY_ITEM_DELETE';
export const POST_CATEGORY_CREATE = 'POST_CATEGORY_CREATE';

export const POST_CATEGORY_LOADING = 'POST_CATEGORY_LOADING';
export const POST_CATEGORY_IS_CREATE = 'POST_CATEGORY_IS_CREATE';
export const POST_CATEGORY_IS_UPDATE = 'POST_CATEGORY_IS_UPDATE';
export const POST_CATEGORY_IS_DELETE = 'POST_CATEGORY_IS_DELETE';
