export const GET_BRAND_LIST = 'GET_BRAND_LIST';
export const GET_BRAND_ITEM = 'GET_BRAND_ITEM';
export const BRAND_ITEM_UPDATE = 'BRAND_ITEM_UPDATE';
export const BRAND_ITEM_IN_ACTIVE = 'BRAND_ITEM_IN_ACTIVE';
export const BRAND_CREATE = 'BRAND_CREATE';

export const BRAND_LOADING = 'BRAND_LOADING';
export const BRAND_IS_CREATE = 'BRAND_IS_CREATE';
export const BRAND_IS_UPDATE = 'BRAND_IS_UPDATE';
export const BRAND_IS_DELETE = 'BRAND_IS_DELETE';
