export const GET_SEO_SETTING_LIST = 'GET_SEO_SETTING_LIST';
export const GET_SEO_SETTING_ITEM = 'GET_SEO_SETTING_ITEM';
export const SEO_SETTING_ITEM_UPDATE = 'SEO_SETTING_ITEM_UPDATE';
export const SEO_SETTING_ITEM_DELETE = 'SEO_SETTING_ITEM_DELETE';
export const SEO_SETTING_CREATE = 'SEO_SETTING_CREATE';

export const SEO_SETTING_LOADING = 'SEO_SETTING_LOADING';
export const SEO_SETTING_IS_CREATE = 'SEO_SETTING_IS_CREATE';
export const SEO_SETTING_IS_UPDATE = 'SEO_SETTING_IS_UPDATE';
export const SEO_SETTING_IS_DELETE = 'SEO_SETTING_IS_DELETE';
