export const SET_STYLE_CRAFT = 'SET_STYLE_CRAFT';
export const SET_CUSTOMIZE_CRAFT = 'SET_CUSTOMIZE_CRAFT';
export const SET_SCREEN_MODE_CRAFT = 'SET_SCREEN_MODE_CRAFT';
export const SET_DOM_IFRAME_CRAFT = 'SET_DOM_IFRAME_CRAFT';
export const SET_STYLE_CUSTOMIZE_BLOCK = 'SET_STYLE_CUSTOMIZE_BLOCK';
