export const GET_PARENT_LIST = 'GET_PARENT_LIST';
export const GET_CHILDREN_LIST = 'GET_CHILDREN_LIST';
export const GET_REPLACEMENT_CLASS_LIST = 'GET_REPLACEMENT_CLASS_LIST';

export const GET_PARENT_ITEM = 'GET_PARENT_ITEM';
export const PARENT_ITEM_UPDATE = 'PARENT_ITEM_UPDATE';
export const PARENT_ITEM_IN_ACTIVE = 'PARENT_ITEM_IN_ACTIVE';
export const PARENT_CREATE = 'PARENT_CREATE';

export const PARENT_LOADING = 'PARENT_LOADING';
export const PARENT_IS_CREATE = 'PARENT_IS_CREATE';
export const PARENT_IS_UPDATE = 'PARENT_IS_UPDATE';
export const PARENT_IS_CANCEL_CLASS = 'PARENT_IS_CANCEL_CLASS';
export const PARENT_IS_REQUEST_A_WORKSHEET = 'PARENT_IS_REQUEST_A_WORKSHEET';
