export const GET_NOTIFICATION_LIST = 'GET_NOTIFICATION_LIST';
export const GET_NOTIFICATION_DETAILS = 'GET_NOTIFICATION_DETAILS';
export const POST_NOTIFICATION_DELETE = 'POST_NOTIFICATION_DELETE';

export const NOTIFICATION_LOADING = 'NOTIFICATION_LOADING';
export const NOTIFICATION_DELETE = 'NOTIFICATION_DELETE';
export const GET_NOTIFICATION_LIST_COUNT = 'GET_NOTIFICATION_LIST_COUNT';
